version: "3.9"  # optional since v1.27.0

services:
  DB:
    container_name: Database
    image: my_sql
    env_file:
      - ".env"
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "1433:1433"
    
  